apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    name: ''
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: 1.9.1
    chart: crossplane
  project: default
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
