
name: 'Azure Pipeline'

on:
  push:
    branches:
      - main
env:
  TF_WORKING_DIR: ./infrastructure/azure/terraform
  HELMFILE_WORKING_DIR: ./k8s/bootstrap/helmfile/charts

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_USE_MSI: true
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1
          terraform_wrapper: false

      - name: terraform init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: terraform validate
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: terraform plan
        run: terraform plan -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: terraform apply
        run: terraform apply -input=false -auto-approve
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.TF_WORKING_DIR }}

  helmfile:
    name: 'Helmfile'
    env:
      KUBECONFIG_FILE: ${{ secrets.AKS_KUBE_CONFIG }}
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Helmfile setup
        uses: mamezou-tech/setup-helmfile@v1.0.0
        with:
          install-helm: no
          install-kubectl: no
          install-helm-plugins: no
          additional-helm-plugins: https://github.com/databus23/helm-diff

      - name: Helmfile validate
        run: |
          helmfile --version
          helm version
          kubectl version --client

      - name : Helmfile apply
        run: |
          helmfile apply
        working-directory: ${{ env.HELMFILE_WORKING_DIR }}